[package]
name = "climbing_stairs"
version = "0.1.0"
authors = ["SonkeWohler <sonke.a.wohler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
